/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jtm_extra14_JNIClass */

#ifndef _Included_jtm_extra14_JNIClass
#define _Included_jtm_extra14_JNIClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jtm_extra14_JNIClass
 * Method:    createArray
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtm_extra14_JNIClass_createArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     jtm_extra14_JNIClass
 * Method:    printArray
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_jtm_extra14_JNIClass_printArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jtm_extra14_JNIClass
 * Method:    printHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jtm_extra14_JNIClass_printHello
  (JNIEnv *, jclass);

/*
 * Class:     jtm_extra14_JNIClass
 * Method:    getValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtm_extra14_JNIClass_getValue
  (JNIEnv *, jobject);

/*
 * Class:     jtm_extra14_JNIClass
 * Method:    setValue
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jtm_extra14_JNIClass_setValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
